apiVersion: apps/v1
kind: Deployment
metadata:
  name: yme-playground
  labels:
    app: yme-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yme-playground
  template:
    metadata:
      labels:
        app: yme-playground
    spec:
      containers:
      - name: yme-playground
        image: msabwat/playground:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: yme-playground
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: yme-playground

